name: ATAIChatbot
channels:
  - nvidia
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - torchaudio
  - cudatoolkit=11.8
  - transformers
  - thefuzz
  - huggingface_hub
  - rdflib
  - scikit-learn
  - pillow
  - numpy
  - accelerate
  - pip
  - pip:
      - Env/speakeasypy-1.0.0-py3-none-any.whl
